name: taskmanager_task_board
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  base:
    path: ../../base
  core:
    path: ../../core
  taskmanager_task_board_data:
    path: lib/src/data

  taskmanger_taskboard_domain:
    path: lib/src/domain

  taskmanager_taskboard_presentation:
    path: lib/src/presentation

  injectable:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  injectable_generator:
