name: task_it_workspace
description: The monorepo root for Task It applications.
environment:
  sdk: ^3.10.7

workspace:
#  - apps/taskdoer
#  - apps/taskmanager
  - packages/base # If you still have this, otherwise remove
  - packages/core
#  - packages/ui_kit
  - packages/features/auth
  - packages/features/auth/lib/src/domain
  - packages/features/auth/lib/src/presentation
#  - packages/features/reports
  - packages/features/base_task_board
  - packages/features/taskdoer_task_board
  - packages/features/taskmanager_task_board
#  - packages/platform/firebase_backend