name: task_it_workspace
description: The monorepo root for Task It applications.
repository: https://github.com/bruc3balo/task_it.git
environment:
  sdk: ^3.10.7

dev_dependencies:
  melos: ^7.3.0

melos:

  scripts:
    build_runner:
      run: melos exec --depends-on="build_runner" -- "dart run build_runner build --delete-conflicting-outputs"
      description: Run code generation (such as Freezed/Json) in all packages.

workspace:
#  - apps/taskdoer
  - apps/task_manager
  - packages/base # If you still have this, otherwise remove
  - packages/core
  - packages/core/lib/src/data_storage
  - packages/core/lib/src/app_log
  - packages/core/lib/src/connectivity
    #Platform
  - packages/platform/platform_hive_data_storage
  - packages/platform/platform_internet_checker_connectivity
  - packages/platform/platform_firebase_authentication
  - packages/platform/platform_firestore_data_storage
#  - packages/ui_kit
    # Features
    # Auth
  - packages/features/auth/auth_data
  - packages/features/auth/auth_domain
  - packages/features/auth/auth_presentation
#  - packages/features/reports
  - packages/features/taskdoer_task_board
  - packages/features/taskdoer_task_board/lib/src/data
  - packages/features/taskdoer_task_board/lib/src/domain
  - packages/features/taskdoer_task_board/lib/src/presentation
   # task_manager_task_board
  - packages/features/task_manager_task_board/task_manager_task_board_data
  - packages/features/task_manager_task_board/task_manager_task_board_domain
  - packages/features/task_manager_task_board/task_manager_task_board_presentation
