name: task_it_workspace
description: The monorepo root for Task It applications.
environment:
  sdk: ^3.10.7

workspace:
#  - apps/taskdoer
#  - apps/taskmanager
  - packages/base # If you still have this, otherwise remove
  - packages/core
  - packages/core/lib/src/data_storage
  - packages/core/lib/src/app_log
  - packages/core/lib/src/connectivity
    #Platform
  - packages/platform/platform_hive_data_storage
#  - packages/ui_kit
  - packages/features/auth
  - packages/features/auth/lib/src/data
  - packages/features/auth/lib/src/domain
  - packages/features/auth/lib/src/presentation
#  - packages/features/reports
  - packages/features/base_task_board
  - packages/features/taskdoer_task_board
  - packages/features/taskdoer_task_board/lib/src/domain
  - packages/features/taskdoer_task_board/lib/src/presentation
  - packages/features/taskmanager_task_board
  - packages/features/taskmanager_task_board/lib/src/domain
  - packages/features/taskmanager_task_board/lib/src/presentation
#  - packages/platform/firebase_backend