name: taskdoer_task_board
description: A starting point for Dart libraries or applications.
version: 1.0.0
resolution: workspace
publish_to: none

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:

  taskdoer_task_board_data:
    path: lib/src/data

  taskdoer_task_board_domain:
    path: lib/src/domain

  taskdoer_task_board_presentation:
    path: lib/src/data

  injectable:


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  injectable_generator:
