name: ui_kit
description: Shared UI components (atoms, molecules) for task_it.
version: 0.0.1
publish_to: 'none' # Prevents accidental publishing to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  loading_animation_widget:

  # Add other UI packages here if needed later
  # google_fonts: ^6.1.0
  # flutter_svg: ^2.0.9

dev_dependencies:
  flutter_lints: ^3.0.0