name: auth
description: Authentication module for task_it
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  auth_domain:
    path: lib/src/domain

  auth_presentation:
    path: lib/src/presentation


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.1
