name: base
description: Foundation module for Task It applications
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
