name: base_task_board
description: Task board base module
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  base:
    path: ../../base

  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.1
