name: platform_firebase_authentication
description: Firebase Authentication
version: 1.0.0
resolution: workspace
environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  core:
    path: ../../core
  firebase_auth: ^6.1.4
  injectable:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
