name: core
description: Abstraction of what task it can do
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  base:
    path: ../base
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  app_log:
    path: lib/src/app_log

  connectivity:
    path: lib/src/connectivity

  data_storage:
    path: lib/src/data_storage

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.1