name: core
description: Abstraction of what task it can do
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.7

dependencies:
  base:
    path: ../base

  app_log:
    path: lib/src/app_log

  connectivity:
    path: lib/src/connectivity

  data_storage:
    path: lib/src/data_storage

  foundation:
    path: lib/src/foundation

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
