name: platform_firestore_data_storage
description: A starting point for Dart libraries or applications.
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  cloud_firestore: ^6.1.2
  core:
    path: ../../core
  json_annotation:
  json_serializable:
  injectable:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  build_runner: