name: task_manager_task_board_domain
description: Task manager task board domain
version: 1.0.0
resolution: workspace
publish_to: none

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  core:
    path: ../../../core
  injectable:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  injectable_generator:
  build_runner:
